### ISSUE TITLE
HTML formatted output of exchange.json

### ISSUE THREAD

**Issue by lmperry** [flywheel-io/exchange#114]
To discuss: For documentation purposes we can parse the `exchange.json` file and write an `html` file, which can can be rendered within the web docs (i.e., confluence). This `exchange.html` file can be stored alongside the `exchange.json` file up on gc, or elsewhere. 

This does not necessarily have to happen within this repo, but maybe it's cheap enough.

**Comment by gsfr** [comment]
Thanks, @lmperry. @maxbailey is on it. 😉 We are actually hoping to tie the result into flywheel.io.

We are planning to use the gh-pages branch in this repo, and I will likely move `exchange.json` into here as well.

**Comment by lmperry** [comment]
That's great to hear. @maxbailey please sync with Imad as we had a talk about that last week. 

If it's helpful (which I'm certain it's not, yet I already wrote it) here's some code to do what I was suggesting: 

```python
import json
from json2html import *
from json2table import *
from pprint import pprint as pp
import os
import urllib
import operator as op


# Define resources
exchange_json_url = 'https://storage.googleapis.com/flywheel-exchange/exchange.json.gz'
exchange_json_file = '/tmp/exchange.json'
html_file = '/tmp/exchange.html'


# Download the json file from the exchange
urllib.urlretrieve(exchange_json_url, exchange_json_file)


# Load exchange data
with open(exchange_json_file, 'r') as ejf:
    exchange_data = json.load(ejf)


# Get a unique set of gear names
names = set([x['name'] for x in exchange_data if x])


# Only get the most recent version of each gear        
latest_gears = []
for n in names:
    this_gear_all = [x for x in exchange_data if x and x['name'] == n]
    this_gear_latest = sorted(this_gear_all, key=op.itemgetter('version'), reverse=True)[0]
    latest_gears.append(this_gear_latest)
    
    
# Generate the html from the exchange json file
if os.path.exists(html_file):
    os.remove(html_file)
for e in sorted(latest_gears, key=lambda k: k['label'].lower()):
    if e:
        descrip = '<p>' + e['description'] + '</p>'
        e.pop('description', None)
        e.pop('flywheel', None)
        html = json2html.convert(json.dumps(e, sort_keys=True), table_attributes="border=\"1\"")
        title = '<h2>' + e.get('label') + '</h2>'
        with open(html_file, 'a') as hf:
            hf.write(' </br> &nbsp; ' + title.encode('utf-8') + descrip.encode('utf-8') + html.encode('utf-8'))

```

**Comment by gsfr** [comment]
Thanks, @lmperry. @maxbailey will actually work on a fully dynamic, JS-based implementation.

**Comment by gsfr** [comment]
@maxbailey I have decided to host the `exchange.json` file in this repo after all.

Here is the updated permalink:
https://raw.githubusercontent.com/flywheel-io/exchange/gh-pages-json/exchange.json

I have also created the `gh-pages` branch here that will host the UI code and seeded it with a trivial `index.html` for you to refine.

Github automatically publishes the contents of the `gh-pages` branch here:
https://flywheel-io.github.io/exchange/

**Comment by gsfr** [comment]
Done.
