### ISSUE TITLE
Migrate away from circle-ci 1 by August 31, 2018

### ISSUE THREAD

**Issue by ryansanford** [flywheel-io/exchange#127]
https://circleci.com/blog/sunsetting-1-0/

**Comment by gsfr** [comment]
And other housekeeping...

- [ ] push images to flywheel-exchange project, not flywheel-io
- [ ] migrate remaining images from flywheel-io to flywheel-exchange

- [ ] migrate rootfs bucket to flywheel-exchange project

- [ ] enforce that manifests reference only tagged upstream images
- [ ] undo docker push in cleanup handler
- [ ] always generate exchange.json

- [ ] move to Docker/Travis/CircleCI 2
